### ISSUE TITLE
user login and password set

### ISSUE THREAD

**Issue by Relentlesslba** [ytitov/grpc-rust-dart-demo#19]
Two functions:
login
set user password

**Comment by Relentlesslba** [comment]
login -> AuthUser, returns AuthResponse

**Comment by ytitov** [comment]
https://crackstation.net/hashing-security.htm

**Comment by Relentlesslba** [comment]
implemented, but when authresponse is false and has no sessionid, message doesn't print anything. Try printing members of message struct explicitly?
