### ISSUE TITLE
update group, assign to user

### ISSUE THREAD

**Issue by ytitov** [ytitov/grpc-rust-dart-demo#8]
- [x] rename
- [x] assign user to group

**Comment by ytitov** [comment]
@Relentlesslba do you think you can implement this?

**Comment by Relentlesslba** [comment]
I'm unable to read the number of rows affected by the execute query in sy-server/src/models/user/mod.rs line 66

**Comment by Relentlesslba** [comment]
ended up using fetch_one instead of execute and checking for error
